name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: xcodebuild clean build CODE_SIGNING_ALLOWED=NO
      env:
        DEVELOPER_DIR: /Applications/Xcode_11.app/Contents/Developer
